GSO_dict = {
   "3D_Dollhouse_Lamp": "purple-white lamp",
   "3D_Dollhouse_Refrigerator": "green wooden refrigerator",
   "3D_Dollhouse_Sofa": "purple wooden sofa",
   "3D_Dollhouse_TablePurple": "purple wooden table",
   "3M_Antislip_Surfacing_Light_Duty_White": "light-gray tape",
   "3M_Vinyl_Tape_Green_1_x_36_yd": "green tape",
   "45oz_RAMEKIN_ASST_DEEP_COLORS": "green shiny bowl",
   "5_HTP": "blue medicine bottle",
   "ACE_Coffee_Mug_Kristen_16_oz_cup": "red coffee mug",
   "AMBERLIGHT_UP_W": "blue sneakers",
   "ASICS_GEL1140V_WhiteBlackSilver": "white-black shoes",
   "ASICS_GEL1140V_WhiteRoyalSilver": "white-black shoes",
   "ASICS_GELAce_Pro_Pearl_WhitePink": "white-pink shoes",
   "ASICS_GELBlur33_20_GS_BlackWhiteSafety_Orange": "black-orange shoes",
   "ASICS_GELBlur33_20_GS_Flash_YellowHot_PunchSilver": "yellow-orange shoes",
   "ASICS_GELChallenger_9_Royal_BlueWhiteBlack": "blue-white shoes",
   "Air_Hogs_Wind_Flyers_Set_Airplane_Red": "red toy airplane",
   "AllergenFree_JarroDophilus": "yellow medicine bottle",
   "Android_Figure_Chrome": "silver android figure",
   "Android_Figure_Orange": "orange android figure",
   "Apples_to_Apples_Kids_Edition": "green-yellow boardgame",
   "Aroma_Stainless_Steel_Milk_Frother_2_Cup": "steel milk frother",
   "Avengers_Gamma_Green_Smash_Fists": "green hulk toy fists",
   "BIA_Cordon_Bleu_White_Porcelain_Utensil_Holder_900028": "white porcelain utensil holder",
   "BIA_Porcelain_Ramekin_With_Glazed_Rim_35_45_oz_cup": "white porcelain ramekin",
   "Threshold_Ramekin_White_Porcelain": "white porcelain ramekin",
   "Utana_5_Porcelain_Ramekin_Large": "white porcelain ramekin",
   "Baby_Elements_Stacking_Cups": "stack of colorful cups",
   "Beyonc_Life_is_But_a_Dream_DVD": "black DVD",
   "Bifidus_Balance_FOS": "purple medicine bottle",
   "Big_Dot_Aqua_Pencil_Case": "green-purple pencil case",
   "Big_Dot_Pink_Pencil_Case": "pink-black pencil case",
   "Big_O_Sponges_Assorted_Cellulose_12_pack": "purple sponge",
   "Black_Decker_CM2035B_12Cup_Thermal_Coffeemaker": "black metal coffee maker",
   "Black_Decker_Stainless_Steel_Toaster_4_Slice": "stainless steel toaster",
   "BlueBlack_Nintendo_3DSXL": "Nintendo gaming console",
   "Blue_Jasmine_Includes_Digital_Copy_UltraViolet_DVD": "white DVD",
   "Bradshaw_International_11642_7_Qt_MP_Plastic_Bowl": "red bowl",
   "Breyer_Horse_Of_The_Year_2015": "toy horse",
   "CARSII": "CARSII",
   "CAR_CARRIER_TRAIN": "black toy train loaded with cars",
   "California_Navy_Tieks_Italian_Leather_Ballet_Flats": "black ballet shoe",
   "Calphalon_Kitchen_Essentials_12_Cast_Iron_Fry_Pan_Black": "white bowl",
   "Threshold_Bead_Cereal_Bowl_White": "white bowl",
   "Threshold_Porcelain_Serving_Bowl_Coupe_White": "white bowl",
   "Chef_Style_Round_Cake_Pan_9_inch_pan": "round cake pan",
   "Chefmate_8_Frypan": "black frypan",
   "Chelsea_BlkHeelPMP_DwxLtZNxLZZ": "golden-black high heel",
   "Chelsea_lo_fl_rdheel_nQ0LPNF1oMw": "red high heel",
   "Chelsea_lo_fl_rdheel_zAQrnhlEfw8": "pink high heel",
   "CoQ10": "white drug bottle",
   "Cole_Hardware_Antislip_Surfacing_Material_White": "toilet paper",
   "Cole_Hardware_Bowl_Scirocco_YellowBlue": "yellow round bowl",
   "Cole_Hardware_Deep_Bowl_Good_Earth_1075": "brown bowl",
   "Cole_Hardware_Dishtowel_BlueWhite": "blue-white dish towel",
   "Cole_Hardware_Dishtowel_Red": "red towel",
   "Cole_Hardware_Dishtowel_Stripe": "red-white striped towel",
   "Tag_Dishtowel_Basket_Weave_Red_18_x_26": "red-white striped towel",
   "Cole_Hardware_Electric_Pot_Assortment_55": "red flower pot",
   "Sapota_Threshold_4_Ceramic_Round_Planter_Red": "red flower pot",
   "Cole_Hardware_Electric_Pot_Cabana_55": "orange clay pot",
   "Cole_Hardware_Orchid_Pot_85": "orange flower pot",
   "Cole_Hardware_Flower_Pot_1025": "gray clay pot",
   "Cole_Hardware_Hammer_Black": "black and yellow hammer",
   "Cole_Hardware_Plant_Saucer_Brown_125": "brown round plate",
   "Cole_Hardware_Plant_Saucer_Glazed_9": "brown round plate",
   "Cole_Hardware_Saucer_Electric": "pink saucer",
   "Cole_Hardware_School_Bell_Solid_Brass_38": "school bell",
   "Colton_Wntr_Chukka_y4jO0I8JQFW": "leather boot",
   "Corningware_CW_by_Corningware_3qt_Oblong_Casserole_Dish_Blue": "rectangular blue casserol dish",
   "Craftsman_Grip_Screwdriver_Phillips_Cushion": "screwdriver",
   "Crosley_Alarm_Clock_Vintage_Metal": "vintage metal alarm clock",
   "Curver_Storage_Bin_Black_Small": "black net basket",
   "DPC_Handmade_Hat_Brown": "black hat",
   "Retail_Leadership_Summit_tQFCizMt6g0": "black hat",
   "DPC_tropical_Trends_Hat": "brown straw hat",
   "Diamond_Visions_Scissors_Red": "red scissors",
   "Dino_3": "toy T-Rex",
   "Dino_4": "toy triceratops",
   "Dino_5": "toy dicynodont dinosaur",
   "Dixie_10_ounce_Bowls_35_ct": "white bowl with purple pattern",
   "Dog": "Dog",
   "Eat_to_Live_The_Amazing_NutrientRich_Program_for_Fast_and_Sustained_Weight_Loss_Revised_Edition_Book": "white book",
   "Ecoforms_Garden_Pot_GP16ATurquois": "turquoise flower pot",
   "Ecoforms_Plant_Container_12_Pot_Nova": "green flower pot",
   "Ecoforms_Plant_Container_QP6CORAL": "red plant container",
   "Ecoforms_Plant_Container_URN_NAT": "brown flower pot",
   "Ecoforms_Plant_Saucer_S20MOCHA": "dark brown saucer",
   "Elephant": "gray elephant toy",
   "Embark_Lunch_Cooler_Blue": "blue cooler bag",
   "F10_TRX_FG_ssscuo9tGxb": "blue-red soccer cleats",
   "F5_TRX_FG": "yellow soccer cleats",
   "FemDophilus": "FemDophilus",
   "GARDEN_SWING": "garden swing",
   "GRANDFATHER_DOLL": "wooden doll",
   "GRANDMOTHER": "wooden doll",
   "GoPro_HERO3_Composite_Cable": "composite cable",
   "Great_Dinos_Triceratops_Toy": "green android mascot",
   "Grreat_Choice_Dog_Double_Dish_Plastic_Blue": "blue dog dish",
   "HeavyDuty_Flashlight": "red flashlight",
   "Hefty_Waste_Basket_Decorative_Bronze_85_liter": "black basket",
   "Hilary": "brown leather boot",
   "MARTIN_WEDGE_LACE_BOOT": "brown leather boot",
   "Rayna_BootieWP": "brown leather boot",
   "Sperry_TopSider_pSUFPWQXPp3": "brown leather boot",
   "Sperry_TopSider_tNB9t6YBUf3": "brown leather boot",
   "Tory_Burch_Sabe_65mm_Bootie_Split_Suede_in_Caramel": "brown leather boot",
   "W_Lou_z0dkC78niiZ": "brown leather boot",
   "Home_Fashions_Washcloth_Linen": "linen cloth",
   "Home_Fashions_Washcloth_Olive_Green": "olive green cloth",
   "Horses_in_Pink_Pencil_Case": "pink pencil case",
   "Imaginext_Castle_Ogre": "green toy ogre",
   "Inositol": "Inositol",
   "JBL_Charge_Speaker_portable_wireless_wired_Green": "green JBL portable speaker",
   "Jansport_School_Backpack_Blue_Streak": "blue and black backpack",
   "KS_Chocolate_Cube_Box_Assortment_By_Neuhaus_2010_Ounces": "white gift box with red straps",
   "Kanex_MultiSync_Wireless_Keyboard": "white keyboard",
   "Kotobuki_Saucer_Dragon_Fly": "pale green saucer",
   "LACING_SHEEP": "toy sheep",
   "Lenovo_Yoga_2_11": "gray laptop",
   "Lovable_Huggable_Cuddly_Boutique_Teddy_Bear_Beige": "brown teddy bear",
   "Magnifying_Glassassrt": "green-orange magnifying glass",
   "Marc_Anthony_Skip_Professional_Oil_of_Morocco_Conditioner_with_Argan_Oil": "blue conditioner bottle",
   "Mens_ASV_Billfish_Boat_Shoe_in_Dark_Brown_Leather_zdHVHXueI3w": "brown leather shoe",
   "Mens_Billfish_3Eye_Boat_Shoe_in_Dark_Tan_wyns9HRcEuH": "brown leather shoe",
   "Mens_Billfish_Slip_On_in_Tan_Beige_aaVUk0tNTv8": "brown leather shoe",
   "NAPA_VALLEY_NAVAJO_SANDAL": "sandal",
   "Neat_Solutions_Character_Bib_2_pack": "white square bowl",
   "Nestle_Nesquik_Chocolate_Powder_Flavored_Milk_Additive_109_Oz_Canister": "yellow nesquik chocolate powder canister",
   "Nickelodeon_Teenage_Mutant_Ninja_Turtles_Leonardo": "teenage mutant ninja turtle figure",
   "Nickelodeon_Teenage_Mutant_Ninja_Turtles_Michelangelo": "teenage mutant ninja turtle figure",
   "Nickelodeon_Teenage_Mutant_Ninja_Turtles_Raphael": "teenage mutant ninja turtle figure",
   "Nikon_1_AW1_w11275mm_Lens_Silver": "nikon camera lens",
   "Nintendo_2DS_Crimson_Red": "black-red nintendo 2ds console",
   "Nintendo_Mario_Action_Figure": "mario action figure",
   "Nintendo_Yoshi_Action_Figure": "green yoshi action figure",
   "Now_Designs_Bowl_Akita_Black": "black-white bowl",
   "Now_Designs_Dish_Towel_Mojave_18_x_28": "green towel",
   "OVAL_XYLOPHONE": "colorful xylophone",
   "OXO_Cookie_Spatula": "black-purple spatula",
   "OXO_Soft_Works_Can_Opener_SnapLock": "black can opener",
   "Object_REmvBDJStub": "green hat with feather",
   "Ocedar_Snap_On_Dust_Pan_And_Brush_1_ct": "white dust pan with brush",
   "Olive_Kids_Birdie_Sidekick_Backpack": "turquoise backpack",
   "Ortho_Forward_Facing": "yellow toy giraffe",
   "Ortho_Forward_Facing_CkAW6rL25xH": "black helmet",
   "Ortho_Forward_Facing_QCaor9ImJ2G": "toy koala",
   "Pennington_Electric_Pot_Cabana_4": "yellow flower pot",
   "Pinwheel_Pencil_Case": "colorful pencil case",
   "Predator_LZ_TRX_FG": "white soccer cleats",
   "Predito_LZ_TRX_FG_W": "white soccer cleats",
   "ProSport_Harness_to_Booster_Seat": "white plate with salad",
   "Provence_Bath_Towel_Royal_Blue": "dark blue towel",
   "REEF_BANTU": "black boot",
   "REEF_BRAIDED_CUSHION": "black flip-flop sandal",
   "Reef_Star_Cushion_Flipflops_Size_8_Black": "black flip-flop sandal",
   "RJ_Rabbit_Easter_Basket_Blue": "white-blue basket",
   "Racoon": "plush racoon",
   "Razer_Abyssus_Ambidextrous_Gaming_Mouse": "black gaming mouse",
   "Razer_Naga_MMO_Gaming_Mouse": "black gaming mouse",
   "Razer_Taipan_Black_Ambidextrous_Gaming_Mouse": "black gaming mouse",
   "Razer_BlackWidow_Stealth_2014_Keyboard_07VFzIVabgh": "black keyboard",
   "Razer_BlackWidow_Ultimate_2014_Mechanical_Gaming_Keyboard": "black keyboard",
   "Razer_Blackwidow_Tournament_Edition_Keyboard": "black keyboard",
   "Razer_Taipan_White_Ambidextrous_Gaming_Mouse": "white gaming mouse",
   "RedBlack_Nintendo_3DSXL": "black and red gameboy",
   "Remington_TStudio_Hair_Dryer": "red hair dryer",
   "Retail_Leadership_Summit": "brown hat",
   "Retail_Leadership_Summit_eCT3zqHYIkX": "gray hat",
   "Rexy_Glove_Heavy_Duty_Gloves_Medium": "blue gloves",
   "Room_Essentials_Bowl_Turquiose": "turquoise bowl",
   "Room_Essentials_Mug_White_Yellow": "white-yellow mug",
   "Room_Essentials_Salad_Plate_Turquoise": "turquoise plate",
   "Rubbermaid_Large_Drainer": "dish drainer",
   "SAMBA_HEMP": "brown shoe",
   "SANDWICH_MEAL": "sandwich on plate",
   "SCHOOL_BUS": "yellow school bus",
   "STACKING_RING": "wooden ring stacker toy",
   "Schleich_African_Black_Rhino": "rhino",
   "Schleich_Bald_Eagle": "bald eagle",
   "Schleich_Hereford_Bull": "brown bull",
   "Schleich_Lion_Action_Figure": "lion",
   "Schleich_S_Bayala_Unicorn_70432": "unicorn",
   "Seagate_Archive_HDD_8_TB_Internal_hard_drive_SATA_6Gbs_35_ST8000AS0002": "metal hard drive storage",
   "Shark": "shark",
   "Weisshai_Great_White_Shark": "shark",
   "Shurtape_30_Day_Removal_UV_Delct_15": "purple tape",
   "Shurtape_Gaffers_Tape_Silver_2_x_60_yd": "gray tape",
   "Sootheze_Cold_Therapy_Elephant": "grey elephant toy",
   "Sootheze_Toasty_Orca": "orca toy",
   "SpiderMan_Titan_Hero_12Inch_Action_Figure_5Hnn4mtkFsP": "spider man action figure",
   "SpiderMan_Titan_Hero_12Inch_Action_Figure_oo1qph4wwiW": "spider man action figure",
   "Squirrel": "toy squirrel",
   "Sushi_Mat": "bamboo sushi mat",
   "Tag_Dishtowel_Dobby_Stripe_Blue_18_x_26": "blue-white striped towel",
   "Tag_Dishtowel_Green": "green-white striped towel",
   "Thomas_Friends_Woodan_Railway_Henry": "green toy train",
   "Threshold_Basket_Natural_Finish_Fabric_Liner_Small": "woven storage basket",
   "Threshold_Bistro_Ceramic_Dinner_Plate_Ruby_Ring": "white-red plate",
   "Threshold_Porcelain_Coffee_Mug_All_Over_Bead_White": "white mug",
   "Threshold_Porcelain_Teapot_White": "white porcelain teapot",
   "Threshold_Salad_Plate_Square_Rim_Porcelain": "white square saucer",
   "Threshold_Textured_Damask_Bath_Towel_Pink": "pink bath towel",
   "Threshold_Tray_Rectangle_Porcelain": "rectangular porcelain tray",
   "Top_Paw_Dog_Bow_Bone_Ceramic_13_fl_oz_total": "white-pink dog bowl",
   "Top_Paw_Dog_Bowl_Blue_Paw_Bone_Ceramic_25_fl_oz_total": "blue dog bowl",
   "Toysmith_Windem_Up_Flippin_Animals_Dog": "white animal dog toy",
   "Travel_Mate_P_series_Notebook": "black laptop",
   "TriStar_Products_PPC_Power_Pressure_Cooker_XL_in_Black": "black power pressure cooker",
   "Unmellow_Yellow_Tieks_Neon_Patent_Leather_Ballet_Flats": "yellow ballet shoe",
   "Vtech_Roll_Learn_Turtle": "green turtle toy",
   "Womens_Canvas_Bahama_in_White_4UyOhP6rYGO": "white shoe",
   "adistar_boost_m": "black sneaker"
}

GSO_dict_attr = {
   "base_set": GSO_dict,
   "choose_set":{
      "towel":{
         "Tag_Dishtowel_Dobby_Stripe_Blue_18_x_26":"blue stripe towel",
         "Tag_Dishtowel_Basket_Weave_Red_18_x_26":"red stripe towel",
         "Tag_Dishtowel_18_x_26":"green stripe towel",
         "Home_Fashions_Washcloth_Linen":"grey wash towel"
      },
      "hat":{
         "Retail_Leadership_Summit_tQFCizMt6g0":"black hat",
         "Retail_Leadership_Summit_eCT3zqHYIkX":"grey hat",
         "Retail_Leadership_Summit":"brown hat"
      },
      "saucer":{
         "Ecoforms_Quadra_Saucer_SQ1_Avocado":"green square saucer plate",
         "Ecoforms_Plant_Saucer_SQ8COR":"red square saucer plate",
         "Ecoforms_Plant_Saucer_SQ1HARVEST":"yellow square saucer plate",
         "Ecoforms_Plate_S20Avocado":"green round plate",
         "Ecoforms_Plant_Saucer_S14NATURAL":"brown round plate",
         "Ecoforms_Plant_Container_S24Turquoise":"blue round plate"
      },
      "plant_container":{
         "Ecoforms_Plant_Container_QP_Turquoise":"blue plant container",
         "Ecoforms_Plant_Container_QP_Harvest":"yellow plant container",
         "Ecoforms_Plant_Container_QP6CORAL":"red plant container",
      },
      "storage":{
         "Seagate_1TB_Wireless_Plus_mobile_device_storage":"metallic mobile device storage",
         "Seagate_1TB_Backup_Plus_portable_drive_Silver":"white mobile device storage",
         "Seagate_1TB_Backup_Plus_portable_drive_Blue":"blue and white mobile device storage"
      },
      "shoe":{
         "SAMBA_HEMP":"brown shoe",
         "SAMOA":"green shoe",
         "Reebok_ZIGTECH_SHARK_MAYHEM360":"white running shoe",
         "Reebok_PUMP_OMNI_LITE_HLS":"black shoe",
         "Reebok_FUELTRAIN":"pink shoe",
         "PureFlow_2_Color_RylPurHibiscusBlkSlvrWht_Size_50":"purple running shoe",
         "F5_TRX_FG":"yellow shoe",
         "ENFR_MID_ENFORCER":"blue shoe",
         "Crazy_Shadow_2_oW4Jd10HFFr":"red shoe"
      },
      "bottle":{
         "Jarrow_Glucosamine_Chondroitin_Combination_120_Caps":"yellow drug bottle",
         "LTyrosine":"red drug bottle",
         "Lactoferrin":"blue drug bottle",
         "Blackcurrant_Lutein":"purple drug bottle"
      },
      "bowl":{
         "Cole_Hardware_Bowl_Scirocco_YellowBlue":"yellow bowl",
         "Cole_Hardware_Deep_Bowl_Good_Earth_1075":"brown bowl",
         "Room_Essentials_Bowl_Turquiose":"blue bowl",
         "Threshold_Bead_Cereal_Bowl_White":"white bowl",
         "Grreatv_Choice_Dog_Bowl_Gray_Bones_Plastic_20_fl_oz_total":"grey dog bowl",
         "Top_Paw_Dog_Bow_Bone_Ceramic_13_fl_oz_total":"pink dog bowl",
         "Grreat_Choice_Dog_Double_Dish_Plastic_Blue":"blue plastic dog bowl"
      },
      "clay_plot": {
         "Cole_Hardware_Electric_Pot_Cabana_55":"orange clay pot",
         "Cole_Hardware_Flower_Pot_1025":"gray clay pot"
      },
      "running shoe":{
         "ASICS_GELAce_Pro_Pearl_WhitePink":"white-pink running shoe",
         "ASICS_GELBlur33_20_GS_BlackWhiteSafety_Orange":"black-orange running shoe",
         "ASICS_GELBlur33_20_GS_Flash_YellowHot_PunchSilver":"yellow-orange running shoe",
         "ASICS_GELChallenger_9_Royal_BlueWhiteBlack":"blue-white running shoe",
         "ASICS_GEL1140V_WhiteBlackSilver":"white-black running shoe",
         "ASICS_GEL1140V_WhiteRoyalSilver": "white-blue running shoe"
      },
      "android_figure":{
         "Android_Figure_Orange":"orange android figure",
         "Great_Dinos_Triceratops_Toy":"green android mascot",
         "Android_Figure_Chrome": "silver android figure"
      },
      "dvd": {
         "Blue_Jasmine_Includes_Digital_Copy_UltraViolet_DVD": "white DVD",
         "Beyonc_Life_is_But_a_Dream_DVD": "black DVD"
      },
      "pencil-case":{
         "Big_Dot_Aqua_Pencil_Case":"green-purple pencil case",
         "Big_Dot_Pink_Pencil_Case":"pink-black pencil case",
         "Horses_in_Pink_Pencil_Case":"pink pencil case",
         "Pinwheel_Pencil_Case":"colorful pencil case"
      },
      "ballet_shoe":{
         "Unmellow_Yellow_Tieks_Neon_Patent_Leather_Ballet_Flats":"yellow ballet shoe",
         "California_Navy_Tieks_Italian_Leather_Ballet_Flats":"black ballet shoe"
      },
      "high_heel":{
         "Chelsea_BlkHeelPMP_DwxLtZNxLZZ":"golden-black high heel",
         "Chelsea_lo_fl_rdheel_nQ0LPNF1oMw":"red high heel",
         "Chelsea_lo_fl_rdheel_zAQrnhlEfw8":"pink high heel"
      },
      "soccer_cleats":{
         "Predator_LZ_TRX_FG":"white-red soccer cleats",
         "Predito_LZ_TRX_FG_W":"white-pink soccer cleats",
         "F10_TRX_FG_ssscuo9tGxb":"blue-red soccer cleats",
         "F5_TRX_FG":"yellow soccer cleats"
      },
      "keyboard":{
         "Razer_BlackWidow_Stealth_2014_Keyboard_07VFzIVabgh":"black keyboard",
         "Kanex_MultiSync_Wireless_Keyboard":"white keyboard"
      },
      "tape": {
         "Shurtape_30_Day_Removal_UV_Delct_15":"purple tape",
         "Shurtape_Gaffers_Tape_Silver_2_x_60_yd":"gray tape",
         "3M_Antislip_Surfacing_Light_Duty_White":"light-gray tape",
         "3M_Vinyl_Tape_Green_1_x_36_yd":"deep-green tape"
      },
      "laptop":{
         "Travel_Mate_P_series_Notebook":"black laptop",
         "Lenovo_Yoga_2_11":"gray laptop"
      }
   }
}
